# Generated by Django 4.1.7 on 2023-03-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_core_app', '0007_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
