# Generated by Django 4.1.7 on 2023-03-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_core_app', '0013_rename_image_profile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='image',
        ),
    ]
