# Generated by Django 4.1.7 on 2023-03-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_core_app', '0015_profile_bio_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
